apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: backup-labeled      
  namespace: kasten-io
spec:
  frequency: "@daily"
  retention:
    daily: 7
    weekly: 4
  selector:
    matchLabels:
      k10.kasten.io/backup: "true" 
  actions:
    - action: backup
      backupParameters:
        profile:
          name: s3-backup-profile
          namespace: kasten-io
    - action: export
      exportParameters:
        exportData:
          enabled: true
        profile:
          name: s3-backup-profile
          namespace: kasten-io

       