apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: mongodb-import
  namespace: kasten-io
spec:
  frequency: "@onDemand"    
  actions:
    - action: import
      importParameters:
        profile:
          name: s3-backup-profile
          namespace: kasten-io
        restoreAfterImport: false