apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: s3-backup-profile
  namespace: kasten-io
spec:
  type: Location
  locationSpec:
    credential:
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: Secret
        name: k10-s3-creds
        namespace: kasten-io
    type: ObjectStore
    objectStore:
      name: ${BUCKET_NAME}
      objectStoreType: S3
      region: ${AWS_REGION}
---
apiVersion: v1
kind: Secret
metadata:
  name: k10-s3-creds
  namespace: kasten-io
type: secrets.kanister.io/aws
stringData:
  aws_access_key_id: "${K10_AWS_ACCESS_KEY_ID}"
  aws_secret_access_key: "${K10_AWS_SECRET_ACCESS_KEY}" 