apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: s3-backup-profile
  namespace: kasten-io
spec:
  type: Location
  location:
    type: objectStore
    objectStore:
      name: k10-s3-backups
      region: ${AWS_REGION}
      bucket: ${BUCKET_NAME}
---
apiVersion: v1
kind: Secret
metadata:
  name: k10-s3-creds
  namespace: kasten-io
type: Opaque
stringData:
  k10-s3-backups: |
    {
      "accessKeyID": "${K10_AWS_ACCESS_KEY_ID}",
      "secretAccessKey": "${K10_AWS_SECRET_ACCESS_KEY}"
    }